<?php
/**
 * Generated approved-brand fill-icon registration list. Do not edit by hand.
 *
 * Regenerated by: node plugins/prc-icon-library/bin/generate-icon-manifest.mjs
 *
 * @package PRC_Icon_Library
 */

// phpcs:ignoreFile -- generated from src/icons/brands/*.svg

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Approved brand fill icons. Keys are kebab-case icon names.
 *
 * @return array<string, array{label: string, file_path: string}>
 */
return array(
	'apple' => array(
		'label'     => 'Apple',
		'file_path' => 'src/icons/brands/apple.svg',
	),
	'bluesky' => array(
		'label'     => 'Bluesky',
		'file_path' => 'src/icons/brands/bluesky.svg',
	),
	'discord' => array(
		'label'     => 'Discord',
		'file_path' => 'src/icons/brands/discord.svg',
	),
	'facebook' => array(
		'label'     => 'Facebook',
		'file_path' => 'src/icons/brands/facebook.svg',
	),
	'github' => array(
		'label'     => 'GitHub',
		'file_path' => 'src/icons/brands/github.svg',
	),
	'google' => array(
		'label'     => 'Google',
		'file_path' => 'src/icons/brands/google.svg',
	),
	'instagram' => array(
		'label'     => 'Instagram',
		'file_path' => 'src/icons/brands/instagram.svg',
	),
	'linkedin' => array(
		'label'     => 'LinkedIn',
		'file_path' => 'src/icons/brands/linkedin.svg',
	),
	'mailchimp' => array(
		'label'     => 'Mailchimp',
		'file_path' => 'src/icons/brands/mailchimp.svg',
	),
	'microsoft' => array(
		'label'     => 'Microsoft',
		'file_path' => 'src/icons/brands/microsoft.svg',
	),
	'slack' => array(
		'label'     => 'Slack',
		'file_path' => 'src/icons/brands/slack.svg',
	),
	'sticker-mule' => array(
		'label'     => 'Sticker Mule',
		'file_path' => 'src/icons/brands/sticker-mule.svg',
	),
	'threads' => array(
		'label'     => 'Threads',
		'file_path' => 'src/icons/brands/threads.svg',
	),
	'tiktok' => array(
		'label'     => 'TikTok',
		'file_path' => 'src/icons/brands/tiktok.svg',
	),
	'twitter' => array(
		'label'     => 'Twitter',
		'file_path' => 'src/icons/brands/twitter.svg',
	),
	'whatsapp' => array(
		'label'     => 'WhatsApp',
		'file_path' => 'src/icons/brands/whatsapp.svg',
	),
	'x-twitter' => array(
		'label'     => 'X Twitter',
		'file_path' => 'src/icons/brands/x-twitter.svg',
	),
	'youtube' => array(
		'label'     => 'YouTube',
		'file_path' => 'src/icons/brands/youtube.svg',
	),
);
