<?php
/**
 * Generated PRC fill-icon registration list. Do not edit by hand.
 *
 * Regenerated by: node plugins/prc-icon-library/bin/generate-icon-manifest.mjs
 *
 * @package PRC_Icon_Library
 */

// phpcs:ignoreFile -- generated from src/icons/prc/*.svg

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Curated fill icons. Keys are kebab-case icon names.
 *
 * @return array<string, array{label: string, file_path: string}>
 */
return array(
	'arrow-right' => array(
		'label'     => 'Arrow Right',
		'file_path' => 'src/icons/prc/arrow-right.svg',
	),
	'angle-up' => array(
		'label'     => 'Angle Up',
		'file_path' => 'src/icons/prc/angle-up.svg',
	),
	'angle-right' => array(
		'label'     => 'Angle Right',
		'file_path' => 'src/icons/prc/angle-right.svg',
	),
	'clipboard-list' => array(
		'label'     => 'Clipboard List',
		'file_path' => 'src/icons/prc/clipboard-list.svg',
	),
	'person-walking-arrow-loop-left' => array(
		'label'     => 'Person Walking Arrow Loop Left',
		'file_path' => 'src/icons/prc/person-walking-arrow-loop-left.svg',
	),
	'people-group' => array(
		'label'     => 'People Group',
		'file_path' => 'src/icons/prc/people-group.svg',
	),
	'person-praying' => array(
		'label'     => 'Person Praying',
		'file_path' => 'src/icons/prc/person-praying.svg',
	),
	'person-booth' => array(
		'label'     => 'Person Booth',
		'file_path' => 'src/icons/prc/person-booth.svg',
	),
	'hands-praying' => array(
		'label'     => 'Hands Praying',
		'file_path' => 'src/icons/prc/hands-praying.svg',
	),
	'user-plus' => array(
		'label'     => 'User Plus',
		'file_path' => 'src/icons/prc/user-plus.svg',
	),
	'backward' => array(
		'label'     => 'Backward',
		'file_path' => 'src/icons/prc/backward.svg',
	),
	'forward' => array(
		'label'     => 'Forward',
		'file_path' => 'src/icons/prc/forward.svg',
	),
	'bookmark' => array(
		'label'     => 'Bookmark',
		'file_path' => 'src/icons/prc/bookmark.svg',
	),
	'bookmark-outline' => array(
		'label'     => 'Bookmark Outline',
		'file_path' => 'src/icons/prc/bookmark-outline.svg',
	),
	'caret-up' => array(
		'label'     => 'Caret Up',
		'file_path' => 'src/icons/prc/caret-up.svg',
	),
	'caret-down' => array(
		'label'     => 'Caret Down',
		'file_path' => 'src/icons/prc/caret-down.svg',
	),
	'caret-right' => array(
		'label'     => 'Caret Right',
		'file_path' => 'src/icons/prc/caret-right.svg',
	),
	'caret-left' => array(
		'label'     => 'Caret Left',
		'file_path' => 'src/icons/prc/caret-left.svg',
	),
	'check' => array(
		'label'     => 'Check',
		'file_path' => 'src/icons/prc/check.svg',
	),
	'chevron-up' => array(
		'label'     => 'Chevron Up',
		'file_path' => 'src/icons/prc/chevron-up.svg',
	),
	'chevron-down' => array(
		'label'     => 'Chevron Down',
		'file_path' => 'src/icons/prc/chevron-down.svg',
	),
	'chevron-left' => array(
		'label'     => 'Chevron Left',
		'file_path' => 'src/icons/prc/chevron-left.svg',
	),
	'chevron-right' => array(
		'label'     => 'Chevron Right',
		'file_path' => 'src/icons/prc/chevron-right.svg',
	),
	'circle-chevron-up' => array(
		'label'     => 'Circle Chevron Up',
		'file_path' => 'src/icons/prc/circle-chevron-up.svg',
	),
	'circle-chevron-down' => array(
		'label'     => 'Circle Chevron Down',
		'file_path' => 'src/icons/prc/circle-chevron-down.svg',
	),
	'circle-chevron-left' => array(
		'label'     => 'Circle Chevron Left',
		'file_path' => 'src/icons/prc/circle-chevron-left.svg',
	),
	'circle-chevron-right' => array(
		'label'     => 'Circle Chevron Right',
		'file_path' => 'src/icons/prc/circle-chevron-right.svg',
	),
	'circle' => array(
		'label'     => 'Circle',
		'file_path' => 'src/icons/prc/circle.svg',
	),
	'circle-outline' => array(
		'label'     => 'Circle Outline',
		'file_path' => 'src/icons/prc/circle-outline.svg',
	),
	'circle-plus' => array(
		'label'     => 'Circle Plus',
		'file_path' => 'src/icons/prc/circle-plus.svg',
	),
	'circle-plus-outline' => array(
		'label'     => 'Circle Plus Outline',
		'file_path' => 'src/icons/prc/circle-plus-outline.svg',
	),
	'circle-minus' => array(
		'label'     => 'Circle Minus',
		'file_path' => 'src/icons/prc/circle-minus.svg',
	),
	'circle-minus-outline' => array(
		'label'     => 'Circle Minus Outline',
		'file_path' => 'src/icons/prc/circle-minus-outline.svg',
	),
	'circle-xmark' => array(
		'label'     => 'Circle Xmark',
		'file_path' => 'src/icons/prc/circle-xmark.svg',
	),
	'circle-xmark-outline' => array(
		'label'     => 'Circle Xmark Outline',
		'file_path' => 'src/icons/prc/circle-xmark-outline.svg',
	),
	'code' => array(
		'label'     => 'Code',
		'file_path' => 'src/icons/prc/code.svg',
	),
	'headphones' => array(
		'label'     => 'Headphones',
		'file_path' => 'src/icons/prc/headphones.svg',
	),
	'house' => array(
		'label'     => 'House',
		'file_path' => 'src/icons/prc/house.svg',
	),
	'list' => array(
		'label'     => 'List',
		'file_path' => 'src/icons/prc/list.svg',
	),
	'magnifying-glass' => array(
		'label'     => 'Magnifying Glass',
		'file_path' => 'src/icons/prc/magnifying-glass.svg',
	),
	'minus' => array(
		'label'     => 'Minus',
		'file_path' => 'src/icons/prc/minus.svg',
	),
	'plus' => array(
		'label'     => 'Plus',
		'file_path' => 'src/icons/prc/plus.svg',
	),
	'moon' => array(
		'label'     => 'Moon',
		'file_path' => 'src/icons/prc/moon.svg',
	),
	'moon-outline' => array(
		'label'     => 'Moon Outline',
		'file_path' => 'src/icons/prc/moon-outline.svg',
	),
	'sun' => array(
		'label'     => 'Sun',
		'file_path' => 'src/icons/prc/sun.svg',
	),
	'sun-outline' => array(
		'label'     => 'Sun Outline',
		'file_path' => 'src/icons/prc/sun-outline.svg',
	),
	'play' => array(
		'label'     => 'Play',
		'file_path' => 'src/icons/prc/play.svg',
	),
	'pause' => array(
		'label'     => 'Pause',
		'file_path' => 'src/icons/prc/pause.svg',
	),
	'print' => array(
		'label'     => 'Print',
		'file_path' => 'src/icons/prc/print.svg',
	),
	'share' => array(
		'label'     => 'Share',
		'file_path' => 'src/icons/prc/share.svg',
	),
	'share-nodes' => array(
		'label'     => 'Share Nodes',
		'file_path' => 'src/icons/prc/share-nodes.svg',
	),
	'xmark' => array(
		'label'     => 'Xmark',
		'file_path' => 'src/icons/prc/xmark.svg',
	),
	'chart-column' => array(
		'label'     => 'Chart Column',
		'file_path' => 'src/icons/prc/chart-column.svg',
	),
	'table' => array(
		'label'     => 'Table',
		'file_path' => 'src/icons/prc/table.svg',
	),
	'compare' => array(
		'label'     => 'Compare',
		'file_path' => 'src/icons/prc/compare.svg',
	),
	'arrow-right-long' => array(
		'label'     => 'Arrow Right Long',
		'file_path' => 'src/icons/prc/arrow-right-long.svg',
	),
	'circle-check' => array(
		'label'     => 'Circle Check',
		'file_path' => 'src/icons/prc/circle-check.svg',
	),
	'circle-check-outline' => array(
		'label'     => 'Circle Check Outline',
		'file_path' => 'src/icons/prc/circle-check-outline.svg',
	),
	'circle-x' => array(
		'label'     => 'Circle X',
		'file_path' => 'src/icons/prc/circle-x.svg',
	),
	'circle-x-outline' => array(
		'label'     => 'Circle X Outline',
		'file_path' => 'src/icons/prc/circle-x-outline.svg',
	),
	'graduation-cap' => array(
		'label'     => 'Graduation Cap',
		'file_path' => 'src/icons/prc/graduation-cap.svg',
	),
	'arrows-rotate' => array(
		'label'     => 'Arrows Rotate',
		'file_path' => 'src/icons/prc/arrows-rotate.svg',
	),
	'arrow-rotate-left' => array(
		'label'     => 'Arrow Rotate Left',
		'file_path' => 'src/icons/prc/arrow-rotate-left.svg',
	),
	'arrow-rotate-right' => array(
		'label'     => 'Arrow Rotate Right',
		'file_path' => 'src/icons/prc/arrow-rotate-right.svg',
	),
	'up-right-and-down-left-from-center' => array(
		'label'     => 'Up Right And Down Left From Center',
		'file_path' => 'src/icons/prc/up-right-and-down-left-from-center.svg',
	),
	'search' => array(
		'label'     => 'Search',
		'file_path' => 'src/icons/prc/search.svg',
	),
	'star' => array(
		'label'     => 'Star',
		'file_path' => 'src/icons/prc/star.svg',
	),
	'star-outline' => array(
		'label'     => 'Star Outline',
		'file_path' => 'src/icons/prc/star-outline.svg',
	),
	'download' => array(
		'label'     => 'Download',
		'file_path' => 'src/icons/prc/download.svg',
	),
	'file' => array(
		'label'     => 'File',
		'file_path' => 'src/icons/prc/file.svg',
	),
	'file-outline' => array(
		'label'     => 'File Outline',
		'file_path' => 'src/icons/prc/file-outline.svg',
	),
	'video' => array(
		'label'     => 'Video',
		'file_path' => 'src/icons/prc/video.svg',
	),
	'clipboard' => array(
		'label'     => 'Clipboard',
		'file_path' => 'src/icons/prc/clipboard.svg',
	),
	'clipboard-outline' => array(
		'label'     => 'Clipboard Outline',
		'file_path' => 'src/icons/prc/clipboard-outline.svg',
	),
	'link' => array(
		'label'     => 'Link',
		'file_path' => 'src/icons/prc/link.svg',
	),
	'presentation-screen' => array(
		'label'     => 'Presentation Screen',
		'file_path' => 'src/icons/prc/presentation-screen.svg',
	),
	'file-pdf' => array(
		'label'     => 'File PDF',
		'file_path' => 'src/icons/prc/file-pdf.svg',
	),
	'file-pdf-outline' => array(
		'label'     => 'File PDF Outline',
		'file_path' => 'src/icons/prc/file-pdf-outline.svg',
	),
	'upload' => array(
		'label'     => 'Upload',
		'file_path' => 'src/icons/prc/upload.svg',
	),
	'arrow-down-up-across-line' => array(
		'label'     => 'Arrow Down Up Across Line',
		'file_path' => 'src/icons/prc/arrow-down-up-across-line.svg',
	),
	'arrow-up-a-z' => array(
		'label'     => 'Arrow Up A Z',
		'file_path' => 'src/icons/prc/arrow-up-a-z.svg',
	),
	'arrow-up-right-from-square' => array(
		'label'     => 'Arrow Up Right From Square',
		'file_path' => 'src/icons/prc/arrow-up-right-from-square.svg',
	),
	'bars-progress' => array(
		'label'     => 'Bars Progress',
		'file_path' => 'src/icons/prc/bars-progress.svg',
	),
	'bars' => array(
		'label'     => 'Bars',
		'file_path' => 'src/icons/prc/bars.svg',
	),
	'bullhorn' => array(
		'label'     => 'Bullhorn',
		'file_path' => 'src/icons/prc/bullhorn.svg',
	),
	'calendar-week' => array(
		'label'     => 'Calendar Week',
		'file_path' => 'src/icons/prc/calendar-week.svg',
	),
	'circle-play' => array(
		'label'     => 'Circle Play',
		'file_path' => 'src/icons/prc/circle-play.svg',
	),
	'circle-play-outline' => array(
		'label'     => 'Circle Play Outline',
		'file_path' => 'src/icons/prc/circle-play-outline.svg',
	),
	'circle-question' => array(
		'label'     => 'Circle Question',
		'file_path' => 'src/icons/prc/circle-question.svg',
	),
	'circle-question-outline' => array(
		'label'     => 'Circle Question Outline',
		'file_path' => 'src/icons/prc/circle-question-outline.svg',
	),
	'cookie-bite' => array(
		'label'     => 'Cookie Bite',
		'file_path' => 'src/icons/prc/cookie-bite.svg',
	),
	'database' => array(
		'label'     => 'Database',
		'file_path' => 'src/icons/prc/database.svg',
	),
	'diamond-turn-right' => array(
		'label'     => 'Diamond Turn Right',
		'file_path' => 'src/icons/prc/diamond-turn-right.svg',
	),
	'earth-americas' => array(
		'label'     => 'Earth Americas',
		'file_path' => 'src/icons/prc/earth-americas.svg',
	),
	'file-arrow-down' => array(
		'label'     => 'File Arrow Down',
		'file_path' => 'src/icons/prc/file-arrow-down.svg',
	),
	'file-lines' => array(
		'label'     => 'File Lines',
		'file_path' => 'src/icons/prc/file-lines.svg',
	),
	'file-lines-outline' => array(
		'label'     => 'File Lines Outline',
		'file_path' => 'src/icons/prc/file-lines-outline.svg',
	),
	'filter' => array(
		'label'     => 'Filter',
		'file_path' => 'src/icons/prc/filter.svg',
	),
	'fingerprint' => array(
		'label'     => 'Fingerprint',
		'file_path' => 'src/icons/prc/fingerprint.svg',
	),
	'fire' => array(
		'label'     => 'Fire',
		'file_path' => 'src/icons/prc/fire.svg',
	),
	'hat-wizard' => array(
		'label'     => 'Hat Wizard',
		'file_path' => 'src/icons/prc/hat-wizard.svg',
	),
	'icons' => array(
		'label'     => 'Icons',
		'file_path' => 'src/icons/prc/icons.svg',
	),
	'layer-group' => array(
		'label'     => 'Layer Group',
		'file_path' => 'src/icons/prc/layer-group.svg',
	),
	'lock' => array(
		'label'     => 'Lock',
		'file_path' => 'src/icons/prc/lock.svg',
	),
	'map' => array(
		'label'     => 'Map',
		'file_path' => 'src/icons/prc/map.svg',
	),
	'map-outline' => array(
		'label'     => 'Map Outline',
		'file_path' => 'src/icons/prc/map-outline.svg',
	),
	'newspaper' => array(
		'label'     => 'Newspaper',
		'file_path' => 'src/icons/prc/newspaper.svg',
	),
	'newspaper-outline' => array(
		'label'     => 'Newspaper Outline',
		'file_path' => 'src/icons/prc/newspaper-outline.svg',
	),
	'palette' => array(
		'label'     => 'Palette',
		'file_path' => 'src/icons/prc/palette.svg',
	),
	'passport' => array(
		'label'     => 'Passport',
		'file_path' => 'src/icons/prc/passport.svg',
	),
	'pen-to-square' => array(
		'label'     => 'Pen To Square',
		'file_path' => 'src/icons/prc/pen-to-square.svg',
	),
	'pen-to-square-outline' => array(
		'label'     => 'Pen To Square Outline',
		'file_path' => 'src/icons/prc/pen-to-square-outline.svg',
	),
	'rectangle-ad' => array(
		'label'     => 'Rectangle Ad',
		'file_path' => 'src/icons/prc/rectangle-ad.svg',
	),
	'recycle' => array(
		'label'     => 'Recycle',
		'file_path' => 'src/icons/prc/recycle.svg',
	),
	'signs-post' => array(
		'label'     => 'Signs Post',
		'file_path' => 'src/icons/prc/signs-post.svg',
	),
	'square-check' => array(
		'label'     => 'Square Check',
		'file_path' => 'src/icons/prc/square-check.svg',
	),
	'square-check-outline' => array(
		'label'     => 'Square Check Outline',
		'file_path' => 'src/icons/prc/square-check-outline.svg',
	),
	'tag' => array(
		'label'     => 'Tag',
		'file_path' => 'src/icons/prc/tag.svg',
	),
	'tags' => array(
		'label'     => 'Tags',
		'file_path' => 'src/icons/prc/tags.svg',
	),
	'temperature-three-quarters' => array(
		'label'     => 'Temperature Three Quarters',
		'file_path' => 'src/icons/prc/temperature-three-quarters.svg',
	),
	'timeline' => array(
		'label'     => 'Timeline',
		'file_path' => 'src/icons/prc/timeline.svg',
	),
	'trash-can' => array(
		'label'     => 'Trash Can',
		'file_path' => 'src/icons/prc/trash-can.svg',
	),
	'trash-can-outline' => array(
		'label'     => 'Trash Can Outline',
		'file_path' => 'src/icons/prc/trash-can-outline.svg',
	),
	'user-check' => array(
		'label'     => 'User Check',
		'file_path' => 'src/icons/prc/user-check.svg',
	),
	'user-gear' => array(
		'label'     => 'User Gear',
		'file_path' => 'src/icons/prc/user-gear.svg',
	),
	'user-graduate' => array(
		'label'     => 'User Graduate',
		'file_path' => 'src/icons/prc/user-graduate.svg',
	),
	'user-lock' => array(
		'label'     => 'User Lock',
		'file_path' => 'src/icons/prc/user-lock.svg',
	),
	'users-gear' => array(
		'label'     => 'Users Gear',
		'file_path' => 'src/icons/prc/users-gear.svg',
	),
	'users-line' => array(
		'label'     => 'Users Line',
		'file_path' => 'src/icons/prc/users-line.svg',
	),
	'users-viewfinder' => array(
		'label'     => 'Users Viewfinder',
		'file_path' => 'src/icons/prc/users-viewfinder.svg',
	),
	'window-restore' => array(
		'label'     => 'Window Restore',
		'file_path' => 'src/icons/prc/window-restore.svg',
	),
	'window-restore-outline' => array(
		'label'     => 'Window Restore Outline',
		'file_path' => 'src/icons/prc/window-restore-outline.svg',
	),
	'yin-yang' => array(
		'label'     => 'Yin Yang',
		'file_path' => 'src/icons/prc/yin-yang.svg',
	),
	'arrow-down-short-wide' => array(
		'label'     => 'Arrow Down Short Wide',
		'file_path' => 'src/icons/prc/arrow-down-short-wide.svg',
	),
	'arrow-up-short-wide' => array(
		'label'     => 'Arrow Up Short Wide',
		'file_path' => 'src/icons/prc/arrow-up-short-wide.svg',
	),
	'bars-staggered' => array(
		'label'     => 'Bars Staggered',
		'file_path' => 'src/icons/prc/bars-staggered.svg',
	),
	'chart-pie' => array(
		'label'     => 'Chart Pie',
		'file_path' => 'src/icons/prc/chart-pie.svg',
	),
	'chart-simple' => array(
		'label'     => 'Chart Simple',
		'file_path' => 'src/icons/prc/chart-simple.svg',
	),
	'circle-dot' => array(
		'label'     => 'Circle Dot',
		'file_path' => 'src/icons/prc/circle-dot.svg',
	),
	'circle-dot-outline' => array(
		'label'     => 'Circle Dot Outline',
		'file_path' => 'src/icons/prc/circle-dot-outline.svg',
	),
	'clock' => array(
		'label'     => 'Clock',
		'file_path' => 'src/icons/prc/clock.svg',
	),
	'clock-rotate-left' => array(
		'label'     => 'Clock Rotate Left',
		'file_path' => 'src/icons/prc/clock-rotate-left.svg',
	),
	'clock-outline' => array(
		'label'     => 'Clock Outline',
		'file_path' => 'src/icons/prc/clock-outline.svg',
	),
	'clone' => array(
		'label'     => 'Clone',
		'file_path' => 'src/icons/prc/clone.svg',
	),
	'clone-outline' => array(
		'label'     => 'Clone Outline',
		'file_path' => 'src/icons/prc/clone-outline.svg',
	),
	'comment' => array(
		'label'     => 'Comment',
		'file_path' => 'src/icons/prc/comment.svg',
	),
	'comment-outline' => array(
		'label'     => 'Comment Outline',
		'file_path' => 'src/icons/prc/comment-outline.svg',
	),
	'credit-card' => array(
		'label'     => 'Credit Card',
		'file_path' => 'src/icons/prc/credit-card.svg',
	),
	'credit-card-outline' => array(
		'label'     => 'Credit Card Outline',
		'file_path' => 'src/icons/prc/credit-card-outline.svg',
	),
	'i-cursor' => array(
		'label'     => 'I Cursor',
		'file_path' => 'src/icons/prc/i-cursor.svg',
	),
	'image' => array(
		'label'     => 'Image',
		'file_path' => 'src/icons/prc/image.svg',
	),
	'image-outline' => array(
		'label'     => 'Image Outline',
		'file_path' => 'src/icons/prc/image-outline.svg',
	),
	'pen' => array(
		'label'     => 'Pen',
		'file_path' => 'src/icons/prc/pen.svg',
	),
	'shield-halved' => array(
		'label'     => 'Shield Halved',
		'file_path' => 'src/icons/prc/shield-halved.svg',
	),
	'sliders' => array(
		'label'     => 'Sliders',
		'file_path' => 'src/icons/prc/sliders.svg',
	),
	'stopwatch' => array(
		'label'     => 'Stopwatch',
		'file_path' => 'src/icons/prc/stopwatch.svg',
	),
	'bell' => array(
		'label'     => 'Bell',
		'file_path' => 'src/icons/prc/bell.svg',
	),
	'bell-outline' => array(
		'label'     => 'Bell Outline',
		'file_path' => 'src/icons/prc/bell-outline.svg',
	),
	'bell-slash' => array(
		'label'     => 'Bell Slash',
		'file_path' => 'src/icons/prc/bell-slash.svg',
	),
	'bell-slash-outline' => array(
		'label'     => 'Bell Slash Outline',
		'file_path' => 'src/icons/prc/bell-slash-outline.svg',
	),
	'envelope' => array(
		'label'     => 'Envelope',
		'file_path' => 'src/icons/prc/envelope.svg',
	),
	'envelope-outline' => array(
		'label'     => 'Envelope Outline',
		'file_path' => 'src/icons/prc/envelope-outline.svg',
	),
	'envelope-open' => array(
		'label'     => 'Envelope Open',
		'file_path' => 'src/icons/prc/envelope-open.svg',
	),
	'envelope-open-outline' => array(
		'label'     => 'Envelope Open Outline',
		'file_path' => 'src/icons/prc/envelope-open-outline.svg',
	),
	'envelope-open-text' => array(
		'label'     => 'Envelope Open Text',
		'file_path' => 'src/icons/prc/envelope-open-text.svg',
	),
	'envelope-circle-check' => array(
		'label'     => 'Envelope Circle Check',
		'file_path' => 'src/icons/prc/envelope-circle-check.svg',
	),
	'inbox' => array(
		'label'     => 'Inbox',
		'file_path' => 'src/icons/prc/inbox.svg',
	),
	'paper-plane' => array(
		'label'     => 'Paper Plane',
		'file_path' => 'src/icons/prc/paper-plane.svg',
	),
	'paper-plane-outline' => array(
		'label'     => 'Paper Plane Outline',
		'file_path' => 'src/icons/prc/paper-plane-outline.svg',
	),
	'card' => array(
		'label'     => 'Card',
		'file_path' => 'src/icons/prc/card.svg',
	),
);
